version: '3.4'

services:
  greeter.api:
    image: ${DOCKER_REGISTRY-}greeterapi
    build:
      context: .
      dockerfile: Greeter.Api/Dockerfile
    ports:
      - "53000:50001"
      
  greeter.api-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "greeter-api", "-app-port", "80", "-app-protocol", "http" ]
    depends_on:
      - greeter.api
    network_mode: "service:greeter.api"

  greeter.service:
    image: ${DOCKER_REGISTRY-}greeterservice
    build:
      context: .
      dockerfile: Greeter.Service/Dockerfile
    ports:
      - "54000:50001"
      
  greeter.service-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "greeter-service", "-app-port", "80", "-app-protocol", "grpc" ]
    depends_on:
      - greeter.service
    network_mode: "service:greeter.service"